/*
 $Id: GelElectrophoresisData.java 3207 2009-04-09 06:48:11Z gregory $

 Copyright (C) 2007 Gregory Vincic, Olle Mansson

 This file is part of Proteios.
 Available at http://www.proteios.org/

 Proteios is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 Proteios is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 02111-1307, USA.
 */
package org.proteios.core.data;


/**
 * This represents a gel object which is generated by a separation event.
 * 
 * @author Olle
 * @version 2.0
 * @see org.proteios.core.GelElectrophoresis
 * @see <a
 *      href="../../../../../../../development/overview/data/gelelectrophoresis.html">GelElectrophoresis
 *      overview</a>
 * @proteios.modified $Date: 2006-05-31 14:31:54Z $
 * @hibernate.subclass discriminator-value="1"
 */
public class GelElectrophoresisData
		extends SeparationMethodData
{
	public GelElectrophoresisData()
	{}

	// -------------------------------------------
	/**
	 * The denaturatingAgent.
	 */
	private String denaturatingAgent;


	/**
	 * Get the denaturatingAgent.
	 * 
	 * @hibernate.property column="`denaturatingAgent`" type="string"
	 *                     length="255" not-null="false"
	 * @return the denaturatingAgent value
	 */
	public String getDenaturatingAgent()
	{
		return denaturatingAgent;
	}


	/**
	 * Set the denaturatingAgent
	 * 
	 * @param denaturatingAgent The String denaturatingAgent value
	 */
	public void setDenaturatingAgent(String denaturatingAgent)
	{
		this.denaturatingAgent = denaturatingAgent;
	}

	/**
	 * The massStart value indicates the start mass.
	 */
	private Integer massStart;


	/**
	 * Get the massStart value
	 * 
	 * @hibernate.property column="`massStart`" type="int" not-null="false"
	 * @return the massStart value
	 */
	public Integer getMassStartInKiloDaltons()
	{
		return massStart;
	}


	/**
	 * Set the massStart
	 * 
	 * @param massStart The integer massStart value to set.
	 */
	public void setMassStartInKiloDaltons(Integer massStart)
	{
		this.massStart = massStart;
	}

	/**
	 * The massEnd value indicates the end mass.
	 */
	private Integer massEnd;


	/**
	 * Get the massEnd value
	 * 
	 * @hibernate.property column="`massEnd`" type="int" not-null="false"
	 * @return the massStart value
	 */
	public Integer getMassEndInKiloDaltons()
	{
		return massEnd;
	}


	/**
	 * Set the massEnd
	 * 
	 * @param massEnd The integer massEnd value to set.
	 */
	public void setMassEndInKiloDaltons(Integer massEnd)
	{
		this.massEnd = massEnd;
	}

	/**
	 * The percentAcrylamide value indicates the percentage of Acrylamide used.
	 */
	private Integer percentAcrylamide;


	/**
	 * Get the percentAcrylamide value
	 * 
	 * @hibernate.property column="`percentAcrylamide`" type="int"
	 *                     not-null="false"
	 * @return the percentAcrylamide value
	 */
	public Integer getPercentAcrylamide()
	{
		return percentAcrylamide;
	}


	/**
	 * Set the percentAcrylamide
	 * 
	 * @param percentAcrylamide The integer percentAcrylamide value to set.
	 */
	public void setPercentAcrylamide(Integer percentAcrylamide)
	{
		this.percentAcrylamide = percentAcrylamide;
	}

	/**
	 * The proteinAssay.
	 */
	private String proteinAssay;


	/**
	 * Get the proteinAssay.
	 * 
	 * @hibernate.property column="`proteinAssay`" type="string" length="255"
	 *                     not-null="false"
	 * @return the proteinAssay value
	 */
	public String getProteinAssay()
	{
		return proteinAssay;
	}


	/**
	 * Set the proteinAssay
	 * 
	 * @param proteinAssay The String proteinAssay value
	 */
	public void setProteinAssay(String proteinAssay)
	{
		this.proteinAssay = proteinAssay;
	}

	/**
	 * The sizeX value indicates the size along the x direction.
	 */
	private Integer sizeX = null;


	/**
	 * Get the sizeX value
	 * 
	 * @hibernate.property column="`sizeX`" type="int" not-null="false"
	 * @return the sizeX value
	 */
	public Integer getSizeXInCentiMeters()
	{
		return sizeX;
	}


	/**
	 * Set the sizeX
	 * 
	 * @param sizeX The Integer sizeX value to set.
	 */
	public void setSizeXInCentiMeters(Integer sizeX)
	{
		this.sizeX = sizeX;
	}

	/**
	 * The sizeY value indicates the size along the y direction.
	 */
	private Integer sizeY = null;


	/**
	 * Get the sizeY value
	 * 
	 * @hibernate.property column="`sizeY`" type="int" not-null="false"
	 * @return the sizeY value
	 */
	public Integer getSizeYInCentiMeters()
	{
		return sizeY;
	}


	/**
	 * Set the sizeY
	 * 
	 * @param sizeY The Integer sizeY value to set.
	 */
	public void setSizeYInCentiMeters(Integer sizeY)
	{
		this.sizeY = sizeY;
	}

	/**
	 * The solubilizationBuffer.
	 */
	private String solubilizationBuffer;


	/**
	 * Get the solubilizationBuffer.
	 * 
	 * @hibernate.property column="`solubilizationBuffer`" type="string"
	 *                     length="255" not-null="false"
	 * @return the solubilizationBuffer value
	 */
	public String getSolubilizationBuffer()
	{
		return solubilizationBuffer;
	}


	/**
	 * Set the solubilizationBuffer
	 * 
	 * @param solubilizationBuffer The String solubilizationBuffer value
	 */
	public void setSolubilizationBuffer(String solubilizationBuffer)
	{
		this.solubilizationBuffer = solubilizationBuffer;
	}
}
